### ISSUE TITLE
Bump version and publish to npm registry so npm install gets latest sqlite3 version

### ISSUE THREAD

**Issue by mjschock** [strongloop/minkelite#24]
I couldn't run slc start or slc pm until I did an npm install -g https://github.com/strongloop/minkelite because the npm install -g minkelite was getting an earlier version of sqlite3 which didn't work with node 4...

**Comment by rmg** [comment]
@mjschock I've just published [minkelite@1.2.4](https://github.com/strongloop/minkelite/releases/tag/v1.2.4). Let us know if it works for you.

**Comment by mjschock** [comment]
It works now - thanks so much!
